name: Run Indexed Query and Save Output

on:
  workflow_dispatch:
  schedule:
    - cron:  '* */1 * * *'

jobs:
  run-query-and-save:
    runs-on: ubuntu-latest

    steps:
      - name: Set up PostgreSQL
        uses: postgres-actions/setup-postgres@v2
        with:
          postgres-version: '13'  # Change to your PostgreSQL version
          postgres-password: 'nearprotocol'
          postgres-port: 5432

      - name: Run Query
        run: |
          output=$(psql -h  mainnet.db.explorer.indexer.near.dev -U public_readonly -d mainnet_explorer -c "WITH votes as (SELECT receipt_predecessor_account_id as user,  (args->>'args_json')::json->>'candidate' as candidate, MIN(to_timestamp( receipt_included_in_block_timestamp / 1000000000 )) as time FROM action_receipt_actions WHERE receipt_receiver_account_id = 'nominations.ndc-gwg.near' AND action_kind = 'FUNCTION_CALL' AND args ->> 'method_name' = 'upvote' AND (args->>'args_json')::json->>'candidate' = 'vadim.near' GROUP BY receipt_predecessor_account_id, candidate) SELECT * FROM votes ORDER BY time DESC;")
          echo "::set-output name=query_output::$output"
          
      - name: Save Output to JSON file
        run: echo "${{ steps.query.outputs.query_output }}" > output.json
  
      - name: Upload JSON file as artifact
        uses: actions/upload-artifact@v2
        with:
          name: query-output
          path: output.json
