name: Run PostgreSQL Query and Save Output

on:
  workflow_dispatch:
  schedule:
    - cron:  '* */1 * * *'
jobs:
  run-query-and-save:
    runs-on: ubuntu-latest

    steps:
      - name: Run Query and Save Output
        env:
            PGPASSWORD: 'nearprotocol'
        id: query
        run: |
          psql -h mainnet.db.explorer.indexer.near.dev -U public_readonly -d mainnet_explorer -tAc "WITH votes as (SELECT receipt_predecessor_account_id as user,  (args->>'args_json')::json->>'candidate' as candidate, MIN(to_timestamp( receipt_included_in_block_timestamp / 1000000000 )) as time FROM action_receipt_actions WHERE receipt_receiver_account_id = 'nominations.ndc-gwg.near' AND action_kind = 'FUNCTION_CALL' AND args ->> 'method_name' = 'upvote' AND (args->>'args_json')::json->>'candidate' = 'vadim.near' GROUP BY receipt_predecessor_account_id, candidate) SELECT * FROM votes ORDER BY time DESC;"
          > output.json
        shell: bash

      - name: Upload JSON file as artifact
        uses: actions/upload-artifact@v2
        with:
          name: query-output
          path: output.json

          
